config/routes.rb
Rails.application.routes.draw do
  resources :docentes
  resources :turnos
  resources :estado_saluds
  resources :comportamientos
  resources :ciclo_escolars
  resources :alumno_ciclos
  resources :ocupacions
  resources :escolaridads
  resources :parentescos
  resources :tutors
  devise_for :users, :controllers => { :registrations => "users" }
  resources  :users
  resources :grado_grupos

  resources :alumnos do
    get 'alumnos_by_group_grado', :on => :collection
    get 'increase_by_grupo_grado', :on => :collection
    get 'increase_by_ciclo_escolar', :on => :collection
  end

  resources :alumno_tutors do
    get 'search_tutor', :on => :collection
  end

  resources :alumno_hermanos do
    get 'search_alumno', :on => :collection
  end

  resources :alumno_comportamientos do
    get 'search_alumno', :on => :collection
  end

  root  'welcome#index'
  get   'setting' => 'users#profile', as: :user_profile
  match 'setting' => 'users#update', via: [:put, :patch]

end

app/models/alumno_comportamiento.rb
class AlumnoComportamiento < ActiveRecord::Base
  belongs_to :alumno
  belongs_to :comportamiento
end

app/controllers/alumno_comportamientos_controller.rb
class AlumnoComportamientosController < ApplicationController
  
  include ApplicationHelper
  before_action :authenticate_user!
  before_action :search, only: [:show, :edit, :new]
  Root_reportes_comportamiento_directory = Rails.root + 'app/assets/images/reportes_comportamientos'
  before_action :set_alumno_comportamiento, only: [:show, :edit, :update, :destroy]

  # GET /alumno_comportamientos
  # GET /alumno_comportamientos.json
  def index
    if params['search']
      search  = params['search']
      @alumno_comportamientos = AlumnoComportamiento.joins(:alumno).where("alumnos.nombre_completo ILIKE ? OR alumnos.matricula ILIKE ?","%#{search}%", "%#{search}%").paginate(:page => params[:page], :per_page => 8)
    else
      @alumno_comportamientos = AlumnoComportamiento.paginate(:page => params[:page], :per_page => 8)
    end
  end

  # GET /alumno_comportamientos/1
  # GET /alumno_comportamientos/1.json
  def show
  end

  # GET /alumno_comportamientos/new
  def new
    @alumno_comportamiento = AlumnoComportamiento.new
  end

  # GET /alumno_comportamientos/1/edit
  def edit
  end

  # POST /alumno_comportamientos
  # POST /alumno_comportamientos.json
  def create
    @alumno_comportamiento = AlumnoComportamiento.new(alumno_comportamiento_params)
    if params[:file]
      @alumno_comportamiento.fotografia = upload_file_helper(params[:file], Root_reportes_comportamiento_directory)
    end
    respond_to do |format|
      if @alumno_comportamiento.save
        format.html { redirect_to @alumno_comportamiento, notice: 'Reporte fue creado.' }
        format.json { render :show, status: :created, location: @alumno_comportamiento }
      else
        format.html { render :new }
        format.json { render json: @alumno_comportamiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alumno_comportamientos/1
  # PATCH/PUT /alumno_comportamientos/1.json
  def update
    if params[:file]
      @alumno_comportamiento.fotografia = upload_file_helper(params[:file], Root_reportes_comportamiento_directory)
    end
    respond_to do |format|
      if @alumno_comportamiento.update(alumno_comportamiento_params)
        format.html { redirect_to @alumno_comportamiento, notice: 'Reporte fue actualizado.' }
        format.json { render :show, status: :ok, location: @alumno_comportamiento }
      else
        format.html { render :edit }
        format.json { render json: @alumno_comportamiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alumno_comportamientos/1
  # DELETE /alumno_comportamientos/1.json
  def destroy
    #AlumnoComportamiento.destroy_all
    @alumno_comportamiento.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Reporte fue eliminado.' }
      format.json { head :no_content }
    end
  end #alumno_comportamientos_url

  # GET /alumnos/search_alumno
  def search_alumno
    matricula         = params[:matricula] == nil ? '' : params[:matricula]
    apellido_paterno  = params[:apellido_paterno] ==   nil ? '' : params[:apellido_paterno]
    @alumnos          = Alumno.where("matricula ILIKE '%#{matricula}%'").where("apellido_paterno ILIKE '%#{apellido_paterno}%'")
    render "alumno_comportamientos/_search_alumno", :layout => false
  end

  private

    def search
      redirect_to_search_helper(alumno_comportamientos_url)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_alumno_comportamiento
      @alumno_comportamiento = AlumnoComportamiento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alumno_comportamiento_params
      params.require(:alumno_comportamiento).permit(:alumno_id, :comportamiento_id, :fecha, :nota, :fotografia)
    end
end

app/helpers/alumno_comportamientos_helper.rb
module AlumnoComportamientosHelper
end

app/views/alumno_comportamientos/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Buscar alumno
  </div>
  <div class="panel-body">
    <form id="form-search-alumno-comportamiento" method="GET" action="/alumno_comportamientos/search_alumno">
      <div class="row">
        <div class="col-md-6">
          <label>Matricula</label>
          <div>
            <input type="text" name="matricula" placeholder="" class="form-control" />
          </div>
        </div>
        <div class="col-md-6">
          <label>Apellido paterno</label>
          <div class="form-group">
            <input type="text" name="apellido_paterno" placeholder="Lopez" class="form-control" />
          </div>
        </div>
        <div class="col-md-12">
          <input type="submit" value="Buscar" class="btn btn-primary" />
        </div>
      </div>
    </form>
  </div>
</div>

<div id="content-table-search-alumnos">
  <h3>Resultado de la búsqueda</h3>
  <table class="table table-bordered" id="table-search-alumnos">
    <thead>
      <th width="130px">Fotografía</th>
      <th>Matricula</th>
      <th>Nombre completo</th>
      <th></th>
    </thead>
    <tbody></tbody>
  </table>
  <br />
</div>

<%= form_for(@alumno_comportamiento, :html => { :id => "form_comportamiento_alumno" , :multipart => true}) do |f| %>
  <% if @alumno_comportamiento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alumno_comportamiento.errors.count, "error") %> prohibited this alumno_comportamiento from being saved:
      </h2>
      <ul>
      <% @alumno_comportamiento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="panel-default">
    <div class="panel-heading">Datos de alumno</div>
    <div class="panel-body">
      <div id="data-section">
        <div class="row">
          <div class="col-md-9">
            <div class="row">
              <div class="col-md-8">  
              <div class="field">
                  <label>Nombre de alumno</label> 
                  <i class="ion-information-circled" data-toggle="tooltip" data-placement="left" title="Para agregar un alumno, es necesario utilizar la sección 'Buscar alumno'"></i>
                  <% if @alumno_comportamiento.alumno %>
                    <input readonly="readonly" type="text" 
                    name="alumno_nombre_completo" 
                    id="input_alumno_nombre_completo" 
                    class="form-control"
                    value="<%= @alumno_comportamiento.alumno.nombre + ' ' +@alumno_comportamiento.alumno.apellido_paterno + ' ' + @alumno_comportamiento.alumno.apellido_materno %>" />
                  <% else %>
                    <input readonly="readonly" type="text" 
                    name="alumno_nombre_completo" 
                    id="input_alumno_nombre_completo" 
                    class="form-control"
                    value="" />
                  <% end %>
                  <%= f.hidden_field :alumno_id, :id => 'input_alumno_id' %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <div class="field">
                  <%= f.label :comportamiento_id %><br>
                  <%= f.select :comportamiento_id, Comportamiento.all.collect { | x | [x.nombre, x.id]}, {}, :class => 'form-control' %>
                </div>
              </div>
              <div class="col-md-6">
                <div class="field">
                  <%= f.label :fecha %><br>
                  <%= f.date_select :fecha,:start_year => 2010, :end_year => Date.today.year,  :html => { :class => "form-control" } %>
                </div>
              </div>
              <div class="col-md-12">
                <div class="field">
                  <%= f.label :nota %><br>
                  <%= f.text_area :nota, :class => 'form-control', :rows => '8' %>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-3">
            <%= f.label :fotografia, 'Fotografía evidencia' %>
            <div class="form-group">
              <%= image_tag @alumno_comportamiento.fotografia ? "reportes_comportamientos/#{@alumno_comportamiento.fotografia}" : "photo-not-available.gif", :class => 'img-responsive img-thumbnail'%>
            </div>
            <div class="form-group">
              <%= file_field_tag "file", :class => 'form-control' %>
            </div>
            <div class="actions">
              <%= f.submit 'Guardar cambios', :class => 'btn btn-success' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/alumno_comportamientos/_search_alumno.html.erb
<% @alumnos.each do |alumno| %>
<tr>
	<td align="center">
		<%= image_tag alumno.fotografia ? "alumnos/#{alumno.fotografia}" : "unknown_user.png",:class => 'img-responsive img-thumbnail', :width => '60px'%>
	</td>
	<td><%= alumno.matricula %></td>
	<td><%= alumno.nombre_completo %></td>
	<td width="180px">
		<a href="#data-section" id="select-search-alumno">
			Seleccionar
			<input type="hidden" id="alumno_id" value="<%= alumno.id %>">
			<input type="hidden" id="alumno_nombre_completo" value="<%= alumno.nombre_completo %>">
			<input type="hidden" id="alumno_matricula" value="<%= alumno.matricula %>">
		</a>
	</td>
</tr>
<% end %>

app/views/alumno_comportamientos/edit.html.erb
<div class="page-header subnav">
  	<div class="pull-right">
    	<%= link_to 'Regresar', alumno_comportamientos_path, :class => 'btn back' %>
  	</div>
  	<h3>Editar reporte</h3>
</div>

<%= render 'form' %>

app/views/alumno_comportamientos/index.html.erb
<div class="page-header subnav">
  <div class="pull-right">
    <div class="btn-group">
      <%= link_to 'Nuevo', new_alumno_comportamiento_path, :class => 'btn btn-success icon-plus-sign icon-white' %>
      <%= link_to ' Regresar a Alumnos ', alumnos_path, :class => 'btn ion-ios-undo' %> 
      <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">Comportamientos <span class="caret"></span></button>
      <ul class="dropdown-menu">
        <li><a href="<%= comportamientos_path %>"><i class="pull-right icon-eye-open"></i> Listado comportamientos</a></li>
        <li><a href="<%= new_comportamiento_path %>"><i class="pull-right icon-download"></i> Agregar comportamiento</a></li>
      </ul>
    </div>
  </div>
  <h3>Comportamiento de alumnos</h3>
</div>
  <%= will_paginate @alumno_comportamientos %>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Alumno</th>
      <th>Comportamiento</th>
      <th>Fecha</th>
      <th width="50px"></th>
    </tr>
  </thead>
  <tbody>
    <% @alumno_comportamientos.each do |alumno_comportamiento| %>
      <tr class="show-data" value="" href="<%= alumno_comportamiento_path(alumno_comportamiento) %>">
        <td><%= alumno_comportamiento.alumno == nil ? 'No disponible' : alumno_comportamiento.alumno.nombre_completo.capitalize %></td>
        <td><%= alumno_comportamiento.comportamiento == nil ? 'No disponible' : alumno_comportamiento.comportamiento.nombre %></td>
        <td><%= alumno_comportamiento.fecha == '' ? '---' : alumno_comportamiento.fecha %></td>
        <td>
          <div class="btn-group">
          <%= link_to '', edit_alumno_comportamiento_path(alumno_comportamiento), :class => 'btn-icon btn ion-edit' %>
          
            <%= form_tag alumno_comportamiento_path(alumno_comportamiento), :class => 'form-delete-data', :method => :delete do %>
            <buton class="delete-data btn-icon btn ion-trash-a"></buton>
            <% end %>
          
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if @alumno_comportamientos.empty? %>
  Aún no hay datos registrados
<% else %>
<% end %>
  <%= will_paginate @alumno_comportamientos %>

app/views/alumno_comportamientos/new.html.erb
<div class="page-header subnav">
	<div class="pull-right">
    	<%= link_to 'Regresar', alumno_comportamientos_path, :class => 'btn back' %>
  	</div>
  	<h3>Nuevo reporte</h3>
</div>

<%= render 'form' %>

app/views/alumno_comportamientos/show.html.erb
<div class="page-header subnav">
  <div class="pull-right">
    <div class="btn-group">
      <%= link_to 'Editar', edit_alumno_comportamiento_path(@alumno_comportamiento), :class => 'btn' %>
      <%= link_to 'Regresar', alumno_comportamientos_path, :class => 'back btn' %>
    </div>
  </div>
  <h3>Detalles de Reporte</h3>
</div>

<div class="row">
  <div class="col-md-7">
    <% if @alumno_comportamiento.alumno %>
    <table class="table table-bordered">
      <tbody>
        <tr>
          <td width="200px">
            <strong>Alumno:</strong>
          </td>
          <td>
            <%= @alumno_comportamiento.alumno.nombre_completo %>
          </td>
        </tr>
        <tr>
          <td width="200px">
            <strong>Turno:</strong>
          </td>
          <td>
            <% if @alumno_comportamiento.alumno.turno %>
              <%= @alumno_comportamiento.alumno.turno.nombre %>
            <% else %>
              No disponible o eliminado
            <% end %>
          </td>
        </tr>
        <tr>
          <td width="200px">
            <strong>Grado y grupo:</strong>
          </td>
          <td>
            <% if @alumno_comportamiento.alumno.grado_grupo %>
              <%= @alumno_comportamiento.alumno.grado_grupo.grado %>
              <%= @alumno_comportamiento.alumno.grado_grupo.grupo %>
            <% else %>
              No disponible o eliminado
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
    <% else %>
      Alumno no disponible o registro eliminado
    <% end %>
    <table class="table table-bordered">
      <tbody>
        <tr>
          <td width="200px"><strong>Comportamiento:</strong></td>
          <td>
            <%= @alumno_comportamiento.comportamiento ? @alumno_comportamiento.comportamiento.nombre : '---' %>
          </td>
        </tr>
        <tr>
          <td><strong>Código comportamiento:</strong></td>
          <td>
            <%= @alumno_comportamiento.comportamiento ? @alumno_comportamiento.comportamiento.codigo : '---' %></td>
        </tr>
        <tr>
          <td><strong>Fecha:</strong></td>
          <td><%= @alumno_comportamiento.fecha %></td>
        </tr>
        <tr>
          <td><strong>Nota:</strong></td>
          <td><%= @alumno_comportamiento.nota %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="col-md-5">
    <div class="form-group">
      <label>Imagen o fotografía adjunta</label>
      <%= image_tag @alumno_comportamiento.fotografia ? "reportes_comportamientos/#{@alumno_comportamiento.fotografia}" : "photo-not-available.gif", :class => 'img-responsive img-thumbnail'%>
    </div>
  </div>
</div>