config/routes.rb
Rails.application.routes.draw do
  resources :docentes
  resources :turnos
  resources :estado_saluds
  resources :comportamientos
  resources :ciclo_escolars
  resources :alumno_ciclos
  resources :ocupacions
  resources :escolaridads
  resources :parentescos
  resources :tutors
  devise_for :users, :controllers => { :registrations => "users" }
  resources  :users
  resources :grado_grupos

  resources :alumnos do
    get 'alumnos_by_group_grado', :on => :collection
    get 'increase_by_grupo_grado', :on => :collection
    get 'increase_by_ciclo_escolar', :on => :collection
  end

  resources :alumno_tutors do
    get 'search_tutor', :on => :collection
  end

  resources :alumno_hermanos do
    get 'search_alumno', :on => :collection
  end

  resources :alumno_comportamientos do
    get 'search_alumno', :on => :collection
  end

  root  'welcome#index'
  get   'setting' => 'users#profile', as: :user_profile
  match 'setting' => 'users#update', via: [:put, :patch]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/alumno.rb
class Alumno < ActiveRecord::Base
  resourcify
  
  belongs_to 	:estado_salud
  belongs_to 	:grado_grupo
  has_many 		:alumno_tutor, dependent: :nullify
  has_many 		:alumno_comportamiento, dependent: :nullify
  has_many 		:alumno_hermano, dependent: :nullify
  belongs_to 	:ciclo_escolar
  has_many 		:alumno_ciclo, dependent: :nullify
  belongs_to	:turno
end

app/models/alumno_ciclo.rb
class AlumnoCiclo < ActiveRecord::Base
  belongs_to :alumno
  belongs_to :ciclo_escolar
  has_many :alumno_tutor, :class_name => 'AlumnoTutor'
end

app/models/alumno_hermano.rb
class AlumnoHermano < ActiveRecord::Base
  belongs_to :alumno
  belongs_to :hermano, :class_name => "Alumno"
end

app/models/alumno_tutor.rb
class AlumnoTutor < ActiveRecord::Base
  belongs_to :alumno
  belongs_to :tutor
end

app/models/ciclo_escolar.rb
class CicloEscolar < ActiveRecord::Base
	has_many :alumno, dependent: :nullify
	has_many :alumno_ciclo, dependent: :nullify
end

app/models/comportamiento.rb
class Comportamiento < ActiveRecord::Base
	has_many :alumno_comportamiento, dependent: :nullify
end

app/models/docente.rb
class Docente < ActiveRecord::Base
end

app/models/escolaridad.rb
class Escolaridad < ActiveRecord::Base
	has_many :tutor, dependent: :nullify
end

app/models/estado_salud.rb
class EstadoSalud < ActiveRecord::Base
	has_many :alumno, dependent: :nullify
end

app/models/grado_grupo.rb
class GradoGrupo < ActiveRecord::Base
	has_many :alumno, dependent: :nullify
end

app/models/ocupacion.rb
class Ocupacion < ActiveRecord::Base
	has_many :tutor, dependent: :nullify
end

app/models/parentesco.rb
class Parentesco < ActiveRecord::Base
	has_many :tutor, dependent: :nullify
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/turno.rb
class Turno < ActiveRecord::Base
	has_many :alumno_tutor, :class_name => 'AlumnoTutor'
end

app/models/tutor.rb
class Tutor < ActiveRecord::Base
  	belongs_to :alumno
  	belongs_to :escolaridad
  	belongs_to :ocupacion
  	belongs_to :parentesco
	has_many   :alumno_tutor, dependent: :nullify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  has_and_belongs_to_many :roles, :join_table => :users_roles
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/comportamientos_controller.rb
class ComportamientosController < ApplicationController

  include ApplicationHelper
  before_action :authenticate_user!
  before_action :search, only: [:show, :edit, :new]
  before_action :set_comportamiento, only: [:show, :edit, :update, :destroy]
  # GET /comportamientos
  # GET /comportamientos.json
  def index
    if params['search']
      search  = params['search']
      @comportamientos = Comportamiento.where("codigo ILIKE ? OR nombre ILIKE ? OR descripcion ILIKE ?","%#{search}%", "%#{search}%", "%#{search}%").paginate(:page => params[:page], :per_page => 8)
    else
      @comportamientos = Comportamiento.paginate(:page => params[:page], :per_page => 10)
    end
  end

  # GET /comportamientos/1
  # GET /comportamientos/1.json
  def show
  end

  # GET /comportamientos/new
  def new
    @comportamiento = Comportamiento.new
  end

  # GET /comportamientos/1/edit
  def edit
  end

  # POST /comportamientos
  # POST /comportamientos.json
  def create
    @comportamiento = Comportamiento.new(comportamiento_params)
    respond_to do |format|
      if @comportamiento.save
        format.html { redirect_to @comportamiento, notice: 'Comportamiento fue creado.' }
        format.json { render :show, status: :created, location: @comportamiento }
      else
        format.html { render :new }
        format.json { render json: @comportamiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comportamientos/1
  # PATCH/PUT /comportamientos/1.json
  def update
    respond_to do |format|
      if @comportamiento.update(comportamiento_params)
        format.html { redirect_to @comportamiento, notice: 'Comportamiento fue actualizado.' }
        format.json { render :show, status: :ok, location: @comportamiento }
      else
        format.html { render :edit }
        format.json { render json: @comportamiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comportamientos/1
  # DELETE /comportamientos/1.json
  def destroy
    @comportamiento.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Comportamiento fue eleminado.' }
      format.json { head :no_content }
    end
  end #comportamientos_url

  private

    def search
      redirect_to_search_helper(alumnos_url)
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_comportamiento
      @comportamiento = Comportamiento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comportamiento_params
      params.require(:comportamiento).permit(:codigo, :nombre, :descripcion)
    end
end

app/helpers/alumnos_helper.rb
module AlumnosHelper
	def get_age (birthday)
		year = Date.today.year
		return year.to_i  - birthday.strftime('%Y').to_i
	end
	
	def get_matricula
	    year = Time.now.strftime("%y")
	    alumnos = Alumno.all
	    unless alumnos.empty?
	      last_alumno = alumnos.last.matricula
	      last_alumno_year = last_alumno[0, 2]
	      if last_alumno_year == year
	        number = last_alumno.to_i + 1
	      else
	        number = year + '00001'
	      end
	    else
	      number = year + '00001'
	    end
	    return number.to_s
	end
end

app/helpers/comportamientos_helper.rb
module ComportamientosHelper
end

app/helpers/turnos_helper.rb
module TurnosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comportamientos/_form.html.erb
<%= form_for(@comportamiento) do |f| %>
  <% if @comportamiento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comportamiento.errors.count, "error") %> prohibited this comportamiento from being saved:</h2>
      <ul>
      <% @comportamiento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row">
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-headin"></div>
        <div class="panel-body">
          <div class="field">
            <%= f.label :codigo, 'Código' %><br>
            <%= f.text_field :codigo, :class => 'form-control' %>
          </div>
          <div class="field">
            <%= f.label :nombre %><br>
            <%= f.text_field :nombre, :class => 'form-control' %>
          </div>
          <div class="field">
            <%= f.label :descripcion, 'Descripción' %><br>
            <%= f.text_area :descripcion, :class => 'form-control', :rows => '8' %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="actions">
        <%= f.submit 'Guardar cambios', :class => 'btn btn-success btn-block' %>
        <%= link_to 'Regresar', comportamientos_path, :class => 'back btn btn-block' %>
      </div>
    </div>
  </div>
  
<% end %>

app/views/comportamientos/edit.html.erb
<div class="page-header subnav">
  <h3>Editar comportamiento</h3>
</div>

<%= render 'form' %>

app/views/comportamientos/index.html.erb
<div class="page-header subnav">
  <div class="pull-right">
    <div class="btn-group">
      <%= link_to 'Nuevo', new_comportamiento_path, :class => 'btn btn-success icon-plus-sign icon-white' %>
      <%= link_to ' Regresar a Reportes ', alumno_comportamientos_path, :class => 'btn ion-ios-undo' %>      
    </div>
  </div>
  <h3>Comportamientos</h3>
</div>
  <%= will_paginate @comportamientos %>
<table class="table table table-bordered">
  <thead>
    <tr> 
      <th>Codigo</th>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th width="50px"></th>
    </tr>
  </thead>
  <tbody>
    <% @comportamientos.each do |comportamiento| %>
      <tr class="show-data" value="" href="<%= comportamiento_path(comportamiento) %>">
        <td><%= comportamiento.codigo %></td>
        <td><%= comportamiento.nombre %></td>
        <td><%= comportamiento.descripcion %></td>
        <td>
          <div class="btn-group">
            <%= link_to '', edit_comportamiento_path(comportamiento), :class => 'btn-icon btn ion-edit' %>
            
              <%= form_tag comportamiento_path(comportamiento), :class => 'form-delete-data', :method => :delete do %>
              <buton class="delete-data btn-icon btn ion-trash-a"></buton>
              <% end %>
            
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if @comportamientos.empty? %>
  Aún no hay datos registrados
<% else %>
  <%= will_paginate @comportamientos %>
<% end %>

app/views/comportamientos/new.html.erb
<div class="page-header subnav">
  <h3>Nuevo comportamiento</h3>
</div>

<%= render 'form' %>

app/views/comportamientos/show.html.erb
<div class="page-header subnav">
	<div class="pull-right">
	    <div class="btn-group">
	      	<%= link_to 'Editar', edit_comportamiento_path(@comportamiento), :class => 'btn' %> 
	      	<%= link_to 'Regresar', comportamientos_path, :class => 'back btn' %>
	    </div>
	</div>
  	<h3>Detalles de comportamiento</h3>
</div>

<table class="table table-bordered">
	<tbody>
		<tr>
			<td width="200px"><strong>Nombre:</strong></td>
			<td><%= @comportamiento.nombre %></td>
		</tr>
		<tr>
			<td><strong>Descripcion:</strong></td>
			<td><%= @comportamiento.descripcion %></td>
		</tr>
	</tbody>
</table>