config/routes.rb
Rails.application.routes.draw do
  resources :docentes
  resources :turnos
  resources :estado_saluds
  resources :comportamientos
  resources :ciclo_escolars
  resources :alumno_ciclos
  resources :ocupacions
  resources :escolaridads
  resources :parentescos
  resources :tutors
  devise_for :users, :controllers => { :registrations => "users" }
  resources  :users
  resources :grado_grupos

  resources :alumnos do
    get 'alumnos_by_group_grado', :on => :collection
    get 'increase_by_grupo_grado', :on => :collection
    get 'increase_by_ciclo_escolar', :on => :collection
  end

  resources :alumno_tutors do
    get 'search_tutor', :on => :collection
  end

  resources :alumno_hermanos do
    get 'search_alumno', :on => :collection
  end

  resources :alumno_comportamientos do
    get 'search_alumno', :on => :collection
  end

  root  'welcome#index'
  get   'setting' => 'users#profile', as: :user_profile
  match 'setting' => 'users#update', via: [:put, :patch]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/alumno.rb
class Alumno < ActiveRecord::Base
  resourcify
  
  belongs_to 	:estado_salud
  belongs_to 	:grado_grupo
  has_many 		:alumno_tutor, dependent: :nullify
  has_many 		:alumno_comportamiento, dependent: :nullify
  has_many 		:alumno_hermano, dependent: :nullify
  belongs_to 	:ciclo_escolar
  has_many 		:alumno_ciclo, dependent: :nullify
  belongs_to	:turno
end

app/models/alumno_ciclo.rb
class AlumnoCiclo < ActiveRecord::Base
  belongs_to :alumno
  belongs_to :ciclo_escolar
  has_many :alumno_tutor, :class_name => 'AlumnoTutor'
end

app/models/alumno_hermano.rb
class AlumnoHermano < ActiveRecord::Base
  belongs_to :alumno
  belongs_to :hermano, :class_name => "Alumno"
end

app/models/alumno_tutor.rb
class AlumnoTutor < ActiveRecord::Base
  belongs_to :alumno
  belongs_to :tutor
end

app/models/ciclo_escolar.rb
class CicloEscolar < ActiveRecord::Base
	has_many :alumno, dependent: :nullify
	has_many :alumno_ciclo, dependent: :nullify
end

app/models/comportamiento.rb
class Comportamiento < ActiveRecord::Base
	has_many :alumno_comportamiento, dependent: :nullify
end

app/models/docente.rb
class Docente < ActiveRecord::Base
end

app/models/escolaridad.rb
class Escolaridad < ActiveRecord::Base
	has_many :tutor, dependent: :nullify
end

app/models/estado_salud.rb
class EstadoSalud < ActiveRecord::Base
	has_many :alumno, dependent: :nullify
end

app/models/grado_grupo.rb
class GradoGrupo < ActiveRecord::Base
	has_many :alumno, dependent: :nullify
end

app/models/ocupacion.rb
class Ocupacion < ActiveRecord::Base
	has_many :tutor, dependent: :nullify
end

app/models/parentesco.rb
class Parentesco < ActiveRecord::Base
	has_many :tutor, dependent: :nullify
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/turno.rb
class Turno < ActiveRecord::Base
	has_many :alumno_tutor, :class_name => 'AlumnoTutor'
end

app/models/tutor.rb
class Tutor < ActiveRecord::Base
  	belongs_to :alumno
  	belongs_to :escolaridad
  	belongs_to :ocupacion
  	belongs_to :parentesco
	has_many   :alumno_tutor, dependent: :nullify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  has_and_belongs_to_many :roles, :join_table => :users_roles
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/ocupacions_controller.rb
class OcupacionsController < ApplicationController
  
  include ApplicationHelper
  before_action :authenticate_user!
  before_action :search, only: [:show, :edit, :new]
  before_action :set_ocupacion, only: [:show, :edit, :update, :destroy]
  # GET /ocupacions
  # GET /ocupacions.json
  def index
    if params['search']
      search  = params['search']
      @ocupacions = Ocupacion.where("nombre ILIKE ? OR descripcion ILIKE ?","%#{search}%", "%#{search}%").paginate(:page => params[:page], :per_page => 8)
    else
      @ocupacions = Ocupacion.paginate(:page => params[:page], :per_page => 10)
    end
  end

  # GET /ocupacions/1
  # GET /ocupacions/1.json
  def show
  end

  # GET /ocupacions/new
  def new
    @ocupacion = Ocupacion.new
  end

  # GET /ocupacions/1/edit
  def edit
  end

  # POST /ocupacions
  # POST /ocupacions.json
  def create
    @ocupacion = Ocupacion.new(ocupacion_params)
    respond_to do |format|
      if @ocupacion.save
        format.html { redirect_to @ocupacion, notice: 'Ocupacion fue creada.' }
        format.json { render :show, status: :created, location: @ocupacion }
      else
        format.html { render :new }
        format.json { render json: @ocupacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ocupacions/1
  # PATCH/PUT /ocupacions/1.json
  def update
    respond_to do |format|
      if @ocupacion.update(ocupacion_params)
        format.html { redirect_to @ocupacion, notice: 'Ocupacion fue actualizada.' }
        format.json { render :show, status: :ok, location: @ocupacion }
      else
        format.html { render :edit }
        format.json { render json: @ocupacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ocupacions/1
  # DELETE /ocupacions/1.json
  def destroy
    @ocupacion.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Ocupacion fue eliminada.' }
      format.json { head :no_content }
    end
  end #ocupacions_url

  private

    def search
      redirect_to_search_helper(ocupacions_url)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_ocupacion
      @ocupacion = Ocupacion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ocupacion_params
      params.require(:ocupacion).permit(:nombre, :descripcion)
    end
end

app/helpers/alumnos_helper.rb
module AlumnosHelper
	def get_age (birthday)
		year = Date.today.year
		return year.to_i  - birthday.strftime('%Y').to_i
	end
	
	def get_matricula
	    year = Time.now.strftime("%y")
	    alumnos = Alumno.all
	    unless alumnos.empty?
	      last_alumno = alumnos.last.matricula
	      last_alumno_year = last_alumno[0, 2]
	      if last_alumno_year == year
	        number = last_alumno.to_i + 1
	      else
	        number = year + '00001'
	      end
	    else
	      number = year + '00001'
	    end
	    return number.to_s
	end
end

app/helpers/ocupacions_helper.rb
module OcupacionsHelper
end

app/helpers/turnos_helper.rb
module TurnosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ocupacions/_form.html.erb
<%= form_for(@ocupacion) do |f| %>
  <% if @ocupacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ocupacion.errors.count, "error") %> prohibited this ocupacion from being saved:</h2>
      <ul>
      <% @ocupacion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="field">
            <%= f.label :nombre %><br>
            <%= f.text_field :nombre, :class => 'form-control' %>
          </div>
          <div class="field">
            <%= f.label :descripcion %><br>
            <%= f.text_area :descripcion, :class => 'form-control', :rows => '8' %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="actions">
        <%= f.submit 'Guardar cambios', :class => 'btn btn-success btn-block' %>
        <%= link_to 'Regresar', ocupacions_path, :class => 'back btn btn-block' %>
      </div>
    </div>
  </div>

<% end %>

app/views/ocupacions/edit.html.erb
<div class="page-header subnav">
  <h3>Editar ocupación</h3>
</div>

<%= render 'form' %>

app/views/ocupacions/index.html.erb
<div class="page-header subnav">
    <div class="pull-right">
      <div class="btn-group">
        <%= link_to 'Nueva', new_ocupacion_path, :class => 'btn btn-success' %>
      </div>
    </div>
  <h3>Ocupaciones</h3>
</div>
  <%= will_paginate @ocupacions %>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th width="50px"></th>
    </tr>
  </thead>
  <tbody>
    <% @ocupacions.each do |ocupacion| %>
      <tr class="show-data" value="" href="<%= ocupacion_path(ocupacion) %>">
        <td><%= ocupacion.nombre %></td>
        <td><%= ocupacion.descripcion %></td>
        <td>
          <div class="btn-group">
          <%= link_to '', edit_ocupacion_path(ocupacion), :class => 'btn-icon btn ion-edit' %>
          
            <%= form_tag ocupacion_path(ocupacion), :class => 'form-delete-data', :method => :delete do %>
            <button class="delete-data btn-icon btn ion-trash-a"></button>
            <% end %>
          
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if @ocupacions.empty? %>
  Aún no hay datos registrados
<% else %>
  <%= will_paginate @ocupacions %>
<% end %>

app/views/ocupacions/new.html.erb
<div class="page-header subnav">
  <h3>Nuevo ocupación</h3>
</div>

<%= render 'form' %>

app/views/ocupacions/show.html.erb
<div class="page-header subnav">
    <div class="pull-right">
      	<div class="btn-group">
     		<%= link_to 'Editar', edit_ocupacion_path(@ocupacion), :class => 'btn' %>
     		<%= link_to 'Regresar', ocupacions_path, :class => 'back btn' %>
      	</div>
    </div>
  	<h3>Detalles de ocupación</h3>
</div>

<table class="table table-bordered">
	<tbody>
		<tr>
			<td width="150px"><strong>Nombre:</strong></td>
			<td><%= @ocupacion.nombre %></td>
		</tr>
		<tr>
			<td><strong>Descripcion:</strong></td>
			<td><%= @ocupacion.descripcion %></td>
		</tr>
	</tbody>
</table>