config/routes.rb
Rails.application.routes.draw do
  resources :docentes
  resources :turnos
  resources :estado_saluds
  resources :comportamientos
  resources :ciclo_escolars
  resources :alumno_ciclos
  resources :ocupacions
  resources :escolaridads
  resources :parentescos
  resources :tutors
  devise_for :users, :controllers => { :registrations => "users" }
  resources  :users
  resources :grado_grupos

  resources :alumnos do
    get 'alumnos_by_group_grado', :on => :collection
    get 'increase_by_grupo_grado', :on => :collection
    get 'increase_by_ciclo_escolar', :on => :collection
  end

  resources :alumno_tutors do
    get 'search_tutor', :on => :collection
  end

  resources :alumno_hermanos do
    get 'search_alumno', :on => :collection
  end

  resources :alumno_comportamientos do
    get 'search_alumno', :on => :collection
  end

  root  'welcome#index'
  get   'setting' => 'users#profile', as: :user_profile
  match 'setting' => 'users#update', via: [:put, :patch]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/alumno.rb
class Alumno < ActiveRecord::Base
  resourcify
  
  belongs_to 	:estado_salud
  belongs_to 	:grado_grupo
  has_many 		:alumno_tutor, dependent: :nullify
  has_many 		:alumno_comportamiento, dependent: :nullify
  has_many 		:alumno_hermano, dependent: :nullify
  belongs_to 	:ciclo_escolar
  has_many 		:alumno_ciclo, dependent: :nullify
  belongs_to	:turno
end

app/models/alumno_ciclo.rb
class AlumnoCiclo < ActiveRecord::Base
  belongs_to :alumno
  belongs_to :ciclo_escolar
  has_many :alumno_tutor, :class_name => 'AlumnoTutor'
end

app/models/alumno_hermano.rb
class AlumnoHermano < ActiveRecord::Base
  belongs_to :alumno
  belongs_to :hermano, :class_name => "Alumno"
end

app/models/alumno_tutor.rb
class AlumnoTutor < ActiveRecord::Base
  belongs_to :alumno
  belongs_to :tutor
end

app/models/ciclo_escolar.rb
class CicloEscolar < ActiveRecord::Base
	has_many :alumno, dependent: :nullify
	has_many :alumno_ciclo, dependent: :nullify
end

app/models/comportamiento.rb
class Comportamiento < ActiveRecord::Base
	has_many :alumno_comportamiento, dependent: :nullify
end

app/models/docente.rb
class Docente < ActiveRecord::Base
end

app/models/escolaridad.rb
class Escolaridad < ActiveRecord::Base
	has_many :tutor, dependent: :nullify
end

app/models/estado_salud.rb
class EstadoSalud < ActiveRecord::Base
	has_many :alumno, dependent: :nullify
end

app/models/grado_grupo.rb
class GradoGrupo < ActiveRecord::Base
	has_many :alumno, dependent: :nullify
end

app/models/ocupacion.rb
class Ocupacion < ActiveRecord::Base
	has_many :tutor, dependent: :nullify
end

app/models/parentesco.rb
class Parentesco < ActiveRecord::Base
	has_many :tutor, dependent: :nullify
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/turno.rb
class Turno < ActiveRecord::Base
	has_many :alumno_tutor, :class_name => 'AlumnoTutor'
end

app/models/tutor.rb
class Tutor < ActiveRecord::Base
  	belongs_to :alumno
  	belongs_to :escolaridad
  	belongs_to :ocupacion
  	belongs_to :parentesco
	has_many   :alumno_tutor, dependent: :nullify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  has_and_belongs_to_many :roles, :join_table => :users_roles
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/alumno_hermanos_controller.rb
class AlumnoHermanosController < ApplicationController
  include ApplicationHelper
  before_action :search, only: [:show, :edit, :new]
  before_action :set_alumno_hermano, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /alumno_hermanos
  # GET /alumno_hermanos.json
  def index
    if params['search']
      search  = params['search']
      @alumno_hermanos = AlumnoHermano.joins(:hermano).where("nombre_completo ILIKE ? OR matricula ILIKE ?","%#{search}%", "%#{search}%").paginate(:page => params[:page], :per_page => 8)
    else
      @alumno_hermanos = AlumnoHermano.paginate(:page => params[:page], :per_page => 10)
    end
  end

  # GET /alumno_hermanos/1
  # GET /alumno_hermanos/1.json
  def show
  end

  # GET /alumno_hermanos/new
  def new
    @alumno = Alumno.find(params[:alumno_id])
    @alumno_hermano = AlumnoHermano.new
  end

  # GET /alumno_hermanos/1/edit
  def edit
    @alumno = Alumno.find(params[:alumno_id])
  end

  # POST /alumno_hermanos
  # POST /alumno_hermanos.json
  def create
    @alumno_hermano = AlumnoHermano.new(alumno_hermano_params)

    respond_to do |format|
      if @alumno_hermano.save
        format.html { redirect_to @alumno_hermano, notice: 'Registro de hermano fue creado.' }
        format.json { render :show, status: :created, location: @alumno_hermano }
      else
        format.html { render :new }
        format.json { render json: @alumno_hermano.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alumno_hermanos/1
  # PATCH/PUT /alumno_hermanos/1.json
  def update
    respond_to do |format|
      if @alumno_hermano.update(alumno_hermano_params)
        format.html { redirect_to @alumno_hermano, notice: 'Registro de hermano fue actualizado.' }
        format.json { render :show, status: :ok, location: @alumno_hermano }
      else
        format.html { render :edit }
        format.json { render json: @alumno_hermano.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alumno_hermanos/1
  # DELETE /alumno_hermanos/1.json
  def destroy
    @alumno_hermano.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Registro de hermano fue eliminado.' }
      format.json { head :no_content }
    end
  end

  def search_alumno
    matricula         = params[:matricula] == nil ? '' : params[:matricula]
    apellido_paterno  = params[:apellido_paterno] ==   nil ? '' : params[:apellido_paterno]
    @alumnos          = Alumno.where("matricula ILIKE '%#{matricula}%'").where("apellido_paterno ILIKE '%#{apellido_paterno}%'")
    render "alumno_hermanos/_search_alumno", :layout => false
  end

  private

    def search
      redirect_to_search_helper(alumno_hermanos_url)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_alumno_hermano
      @alumno_hermano = AlumnoHermano.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alumno_hermano_params
      params.require(:alumno_hermano).permit(:alumno_id, :hermano_id)
    end
end

app/helpers/alumno_hermanos_helper.rb
module AlumnoHermanosHelper
end

app/helpers/alumnos_helper.rb
module AlumnosHelper
	def get_age (birthday)
		year = Date.today.year
		return year.to_i  - birthday.strftime('%Y').to_i
	end
	
	def get_matricula
	    year = Time.now.strftime("%y")
	    alumnos = Alumno.all
	    unless alumnos.empty?
	      last_alumno = alumnos.last.matricula
	      last_alumno_year = last_alumno[0, 2]
	      if last_alumno_year == year
	        number = last_alumno.to_i + 1
	      else
	        number = year + '00001'
	      end
	    else
	      number = year + '00001'
	    end
	    return number.to_s
	end
end

app/helpers/turnos_helper.rb
module TurnosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/alumno_hermanos/_form.html.erb
<div class="row">
  <div class="col-md-7">
    <div class="panel panel-default">
      <div class="panel-heading">Buscar alumno</div>
      <div class="panel-body">
          <form id="form-search-alumno-hermano" method="GET" action="/alumno_hermanos/search_alumno">
            <div class="row">
                <div class="col-md-6">
                  <label>Matricula</label>
                  <div><input type="text" name="matricula" placeholder="1500001" class="form-control" /></div>
                </div>
                <div class="col-md-6">
                  <label>Apellido paterno</label>
                  <div class="form-group"><input type="text" name="apellido_paterno" placeholder="Lopez" class="form-control" /></div>
                </div>
                <div class="col-md-12">
                  <input type="submit" value="Buscar" class="btn btn-primary" />
                </div>
            </div>
          </form>
      </div>
    </div>
  </div>
  <div class="col-md-5">
    <div class="panel panel-default">
      <div class="panel-heading">
        Datos del alumno
      </div>
      <div class="panel-body">
        <div class="form-group">
          <label>Nombre:</label>
          <%= @alumno.nombre_completo.capitalize %>
        </div>
        <div class="form-group">
          <label>Grado y grupo:</label>
          <% if @alumno.grado_grupo %>
            <%= @alumno.grado_grupo.grado  %>
            <%= @alumno.grado_grupo.grupo  %>
          <% else %>
            No disponible
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="content-table-search-alumnos">
  <h3>Resultado de la búsqueda</h3>
  <table class="table table-bordered" id="table-search-alumnos">
    <thead>
      <th width="130px">Fotografía</th>
      <th>Matricula</th>
      <th>Nombre completo</th>
      <th></th>
    </thead>
    <tbody></tbody>
  </table><br />
</div>

<%= form_for(@alumno_hermano, :html => { :id => "form_comportamiento_alumno_hermano" }) do |f| %>
  <% if @alumno_hermano.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alumno_hermano.errors.count, "error") %> prohibited this alumno_hermano from being saved:</h2>
      <ul>
      <% @alumno_hermano.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h3>Agregar hermano</h3>
  <div class="panel panel-default">
    <div class="panel-heading">
      Datos del hermano    
    </div>
    <div class="panel-body">
      <div id="data-section">
        <div class="row">
          <div class="col-md-8">
            <div class="field">
              <div class="form-group">
                <label>Nombre completo</label>
                <input readonly="readonly" type="text" name="alumno_nombre_completo" 
                id="input_alumno_nombre_completo" class="form-control"
                value="<%= @alumno_hermano.hermano ? @alumno_hermano.hermano.nombre_completo : '' %>" />
              </div>
              <div class="form-group">
                <label>Matricula</label>
                <input readonly="readonly" type="text" class="form-control" id="input_alumno_matricula" name="alumno_matricula"
                value="<%= @alumno_hermano.hermano ? @alumno_hermano.hermano.matricula : '' %>" />
              </div>
              <%= f.hidden_field :hermano_id, :id => 'input_alumno_hermano_id' %>
              <%= f.hidden_field :alumno_id, :value => @alumno.id %>
            </div>
          </div>
          <div class="col-md-4">
            <div class="actions">
              <%= f.submit 'Guardar cambios', :class => 'btn btn-success btn-block' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/alumno_hermanos/_search_alumno.html.erb
<% @alumnos.each do |alumno| %>
<tr>
	<td align="center">
		<%= image_tag alumno.fotografia ? "alumnos/#{alumno.fotografia}" : "unknown_user.png",:class => 'img-responsive img-thumbnail', :width => '60px'%>
	</td>
	<td><%= alumno.matricula %></td>
	<td><%= alumno.nombre_completo %></td>
	<td width="180px">
		<a href="#data-section" id="select-search-alumno">
			Seleccionar
			<input type="hidden" id="alumno_id" value="<%= alumno.id %>">
			<input type="hidden" id="alumno_nombre_completo" value="<%= alumno.nombre_completo %>">
			<input type="hidden" id="alumno_matricula" value="<%= alumno.matricula %>">
		</a>
	</td>
</tr>
<% end %>

app/views/alumno_hermanos/edit.html.erb
<% if @alumno %>
	<div class="page-header subnav">
	  	<div class="pull-right">
	    	<div class="btn-group">
	    		<%= link_to 'Regresar', :back, :class => 'back btn' %> 
	    	</div>
	  	</div>
	 	<h3>Editar relación de alumno y hermano</h3>
	</div>
	<%= render 'form' %>
<% else %>
	No se encontro el alumno <%= link_to 'Ir a Alumnos', alumno_hermanos_path %>
<% end %>

app/views/alumno_hermanos/index.html.erb
<div class="page-header subnav">
  <div class="pull-right">
    <div class="btn-group">
      <%= link_to ' Regresar a Alumnos ', alumnos_path, :class => 'btn ion-ios-undo' %>  
    </div>
  </div>
  <h3>Lista de hermanos y alumno</h3>
</div>
  <%= will_paginate @alumno_hermanos %>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Nombre completo de alumno</th>
      <th>Nombre completo de hermano</th>
      <th width="50px"></th>
    </tr>
  </thead>
  <tbody>
    <% @alumno_hermanos.each do |alumno_hermano| %>
      <tr>
        <td>
          <%= (alumno_hermano.alumno) ? alumno_hermano.alumno.nombre_completo : 'No disponible' %>
        </td>
        <td>
          <%= (alumno_hermano.hermano) ? alumno_hermano.hermano.nombre_completo : 'No disponible' %>
        </td>
        <td>
          <div class="btn-group">
          <% if alumno_hermano.alumno %>
            <%= link_to '', edit_alumno_hermano_path(alumno_hermano, :alumno_id => alumno_hermano.alumno.id), :class => 'btn-icon btn ion-edit'%>
          <% else %>
          <% end %>
          
            <%= form_tag alumno_hermano_path(alumno_hermano), :class => 'form-delete-data', :method => :delete do %>
            <button class="delete-data btn-icon btn ion-trash-a"></button>
            <% end %>
          
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if @alumno_hermanos.empty? %>
  Aún no hay datos registrados
<% else %>
  <%= will_paginate @alumno_hermanos %>
<% end %>

app/views/alumno_hermanos/new.html.erb
<% if @alumno %>
	<div class="page-header subnav">
	  	<div class="pull-right">
	    	<div class="btn-group">
	      		<%= link_to 'Regresar', :back, :class => 'back btn' %>
	    	</div>
	  	</div>
	  	<h3>Relacionar alumno y hermano</h3>
	</div>
	<%= render 'form' %>
<% else %>
	No se encontro el alumno <%= link_to 'Ir a Alumnos', alumno_hermanos_path %>
<% end %>

app/views/alumno_hermanos/show.html.erb
<div class="page-header subnav">
	<% if @alumno_hermano.alumno and @alumno_hermano.hermano %>
	<div class="pull-right">
	    <div class="btn-group">
	      <%= link_to 'Editar', edit_alumno_hermano_path(@alumno_hermano, :alumno_id => @alumno_hermano.alumno.id), :class=> 'btn' %>
	      <%= link_to 'Regresar a detalles de alumno', @alumno_hermano.alumno, :class => 'btn' %>
	    </div>
  	</div>
  	<% else %>
		Ocurrio un error con los datos de alumno y hermano
	<% end %>
  	<h3>Detalles de alumno y hermano</h3>
</div>

<table class="table table-bordered">
	<thead><th colspan="3">Datos de alumno</th></thead>
	<tbody>
		<% if @alumno_hermano.alumno %>
		<tr>
			<td width="180px"><strong>Nombre completo:</strong></td>
			<td><%= @alumno_hermano.alumno.nombre_completo.capitalize %></td>
			<td rowspan="3" width="150px" align="center"><%= link_to 'Ver detalles', alumno_path(@alumno_hermano.alumno) %></td>
		</tr>
		<tr>
			<td width="180px"><strong>Matricula:</strong></td>
			<td><%= @alumno_hermano.alumno.matricula %></td>
		</tr>
		<tr>
			<td><strong>Grado y grupo</strong></td>
			<td>
				<% if @alumno_hermano.alumno.grado_grupo %>
	              <%= @alumno_hermano.alumno.grado_grupo.grado  %>
	              <%= @alumno_hermano.alumno.grado_grupo.grupo  %>
	            <% else %>
	              No disponible
	            <% end %>
			</td>
		</tr>
		<% else %>
			No se encuentra disponible los registros de alumno
		<% end %>
	</tbody>
</table>
<br />
<table class="table table-bordered">
	<thead>
		<th colspan="3">Datos de hermano</th>
	</thead>
	<tbody>
		<% if @alumno_hermano.hermano %>
		<tr>
			<td width="180px"><strong>Nombre completo:</strong></td>
			<td><%= @alumno_hermano.hermano.nombre_completo.capitalize %></td>
			<td rowspan="3" width="150px" align="center"><%= link_to 'Ver detalles', alumno_path(@alumno_hermano.hermano) %></td>
		</tr>
		<tr>
			<td width="180px"><strong>Matricula:</strong></td>
			<td><%= @alumno_hermano.hermano.matricula %></td>
		</tr>
		<tr>
			<td><strong>Grado y grupo</strong></td>
			<td>
				<% if @alumno_hermano.hermano.grado_grupo %>
                  <%= @alumno_hermano.hermano.grado_grupo.grado  %>
                  <%= @alumno_hermano.hermano.grado_grupo.grupo  %>
                <% else %>
          			No disponible
       			<% end %>
			</td>
		</tr>
		<% else %>
			No se encuentra disponible los registros de hermano
		<% end %>
	</tbody>
</table>